### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by leledumbo** [michaliskambi/modern-pascal-introduction#1]
> The logical operators are called and , or , not , xor . Since they also act as bitwise operators, you may need to use parenthesis around some expressions, to avoid confusing the compiler.

The reason is not due to they are also use as bitwise operators (in fac, syntactically both are the same, only the semantics that are different), but due to operator precedence where they're on higher level than relational operators. Thus:

```pascal
 A = 0 and B <> 0
```

would be seen as:

```pascal
((A = (0 and B)) <> 0)
```

instead of:

```pascal
((A = 0) and (B <> 0))
```

by the compiler

**Comment by michaliskambi** [comment]
Thank you! Something was ringing in my head when writing this, that the operator precedence was the root cause, but I couldn't pinpoint it. I reworked the text around, to explain it correctly. Thanks!
