### ISSUE TITLE
Add revision number

### ISSUE THREAD

**Issue by kcthrn** [michaliskambi/modern-pascal-introduction#16]
Just discovered this book. Would you be willing to add some sort of revision number to the html and pdf output?

A simple date of last update would work (yyyy-mm-dd).

**Comment by michaliskambi** [comment]
There is a date at the bottom of the HTML, https://castle-engine.io/modern_pascal_introduction.html . Right now  _Last updated 2021-05-24 16:36:34 +0200_  .

It's not visible as plainly in PDF, but it is there too, in metadata. Click on PDF "Document Properties" or a similar option (depending on how you view PDF), and the date is there. Here's a screenshot how it looks in Firefox embedded PDF viewer.

![Zrzut ekranu z 2021-08-16 11-13-59](https://user-images.githubusercontent.com/1076978/129540355-cac0a990-656f-4534-9b9a-d48cc1b91c01.png)

You can also look at the GitHub history on https://github.com/michaliskambi/modern-pascal-introduction and https://github.com/michaliskambi/modern-pascal-introduction/commits/master , i.e. last commit date.
