### ISSUE TITLE
Conflicting statement

### ISSUE THREAD

**Issue by alpinistbg** [michaliskambi/modern-pascal-introduction#19]
Here, at the end of line 943:

> ... This dirty trick works only in non-virtual methods (that don't call any virtual methods and don't access any fields).

But actually `TObject.Free` calls `TObject.Destroy` which is in turn _virtual_.

**Comment by michaliskambi** [comment]
Thank you!

Indeed the clause _"(that don't call any virtual methods and don't access any fields)"_ was confusing. It was meant to mean _"you cannot call any virtual methods / access fields if `Self` is (possibly) `nil`"_.

I improved the text, also added an example showing it in https://github.com/michaliskambi/modern-pascal-introduction/blob/master/code-samples/method_with_self_nil.lpr . As expected, it works with non-virtual method, but crashes with virtual.

![screenshot 2023-01-18 12-47-41 select](https://user-images.githubusercontent.com/1076978/213164847-96103402-6785-445b-8f1b-1135f68a4515.png)
