### ISSUE TITLE
Some or Same?

### ISSUE THREAD

**Issue by eugeneloza** [michaliskambi/modern-pascal-introduction#2]
(Chapter: 5.4. Free notification)
> Some goes for calling a virtual method, or calling a non-virtual method that accessed a field of a nil instance.

Maybe you've meant "Same goes for"? I couldn't find what could the phrase "some goes for..." mean except when distributing something among some acceptors (e.g. "some money goes to the policeman").

**Comment by michaliskambi** [comment]
Indeed, I wanted to write "Same goes for...":) Spellchecker did not catch such typo:) Fixed, thanks!
