### ISSUE TITLE
Finalizing Russian translation :)

### ISSUE THREAD

**Issue by eugeneloza** [michaliskambi/modern-pascal-introduction#3]
Eventually we're done with basic proof-reading of the translated book :) Next step would be proof-reading it in printed (yeah, I'm an old-school editor... pen-and-paper is still my best friend :)).
However, I'm having some problems compiling the book text. The html version produced by asciidoctor doesn't catch all the syntax (result looks even worse than github-parser) - with no errors specified. Well... there should be a few at least in chapters cross-reference which I hadn't fixed last time I've tried compilation. Moreover I could find no asciidoctor-pdf installed/installable in Debian... And README-pdf.adoc way looks relatively complex for me (not something I can just "take and make" without trial-and-error, so it'll require me to concentrate).
I'll eventually solve those issues, but to speed the things up I'd ask if you could make a temporary pdf for me, if it's not too complex, so that I can print it out and start proof-reading "a semi-final version" without delays for setting-up the whole system.
The up-to-date Russian version is here: https://github.com/eugeneloza/modern-pascal-introduction
I've also made some minor fixes to English version, but I still have to make some backward-fixes for some errors I've made in formatting (mostly accidentally adding unnecessary lines breaks).

**Comment by michaliskambi** [comment]
> Moreover I could find no asciidoctor-pdf installed/installable in Debian... 

Indeed, neither `asciidoctor-pdf` nor `asciidoctor-fopub` are packaged yet, as far as I know. You need to install them yourself, following the instructions in their READMEs. It's fairly straightforward, at least on Linux, in my experience -- but I'm biased, since I was using DocBook before Asciidoctor, so I was familiar with the terminology and software.

I'll generate and send you PDFs shortly!

**Comment by michaliskambi** [comment]
I uploaded the generated output to http://michalis.ii.uni.wroc.pl/~michalis/tmp/ . 

- The files `modern_pascal_introduction_Russian.pdf` and `modern_pascal_introduction_Russian.html` were made just by changing NAME at the beginning of `Makefile`, and then running `make`. So the PDF was made by asciidoctor-fopub, exactly the same version as the one I used to generate my (English) output.

- I also uploaded an alternative PDF version generated by asciidoctor-pdf as `modern_pascal_introduction_Russian_by_asciidoctor-pdf`.

If useful, I could setup a Jenkins job and give you access to it, to automatically generate a PDF every time you commit to the repository? This would be part of https://michalis.ii.uni.wroc.pl/jenkins/ .

**Comment by eugeneloza** [comment]
Thanks a lot! Now I can start working on a printed text right away.
The alternative version looks better to me (it seems to catch the syntax in a better way).
I'm not yet sure I can already start working with Jenkins... Anyway, as soon as I'm done with proof-reading I'll push the translation. Then I'll "publish" the book at a few sites to gather ideas and suggestions for fixes if there would be any.
