### ISSUE TITLE
One more question on the book...

### ISSUE THREAD

**Issue by eugeneloza** [michaliskambi/modern-pascal-introduction#5]
Hi, Michalis!
I'm working on 2nd part of proof-reading the text at the moment, and I've ran into a _not-very-important_ question.

In some examples you use the text like:
`'Note: '+'strings are automatically managed'`
Does it have any specific meaning? What's about automatically managed strings? You mean that they are dynamic strings (unless declared as AnsiString) and are automatically freed when they go out of scope? Or that strings can be both UTF8, UTF32 and other encodings? Or maybe, you meant that concatenation is preformed by plus sign?

**Comment by michaliskambi** [comment]
"string" is the same thing as "AnsiString". At least when compiled with {$H+}, as I advice in all examples (It's a pity that it's not the default mode of FPC, IMHO. Both Lazarus and Castle Game Engine build tool by default pass command-line options to FPC that effectively make all code have {$H+} defined).

By "automatically managed" I essentially meant all those things you mentioned...
- That they are automatically freed.
- And automatically allocated (when doing A + B), 
- and reference counted (when doing A := B), 
- and copied-on-write (when doing B[10] := 'a' and "B" had reference count > 1) ... 

I didn't want to go into the exact details, as the idea of the AnsiString implementation is that 99% of the time you can just forget about it:)

I did not really think about the automatic encoding management (UTF8 etc.) when writing this, as I didn't use it intensively yet, but yes -- that is also something that happens automatically and it *should* be something invisible ("just works") to the user.

**Comment by eugeneloza** [comment]
Thanks a lot!
