### ISSUE TITLE
Finished Russian translation

### ISSUE THREAD

**Issue by eugeneloza** [michaliskambi/modern-pascal-introduction#7]
Finally I've finished copying proof-reading results to electronic version. I've made several additions/improvements to English text also, but I still need some more time to make it merge smoothly :) I.e. introduce the changes made since we've started working on it.

Yes, working with the text showed that it can still use additional proof-redaing, but I'll return here later. If you could generate an up-to-date PDF that'd be very nice :) https://github.com/eugeneloza/modern-pascal-introduction

**Comment by michaliskambi** [comment]
Sure! I uploaded the latest version to
* https://michalis.ii.uni.wroc.pl/~michalis/tmp/modern_pascal_introduction_Russian.html
* https://michalis.ii.uni.wroc.pl/~michalis/tmp/modern_pascal_introduction_Russian.pdf
